version: "3"
services:
  p4tg:
    container_name: p4tg-frontend
    build: .
    ports:
      - 80:80
    volumes:
      - ./:/app
      - /app/node_modules
    #command: bash -c "npm start"
    command: bash -c "npm run build && serve -s build -p 80"
